version: '1.0'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - hmall
networks:
  hmall:
    name: hmall
    